### ISSUE TITLE
Add Uniswap V2 pool on Kovan testnet

### ISSUE THREAD

**Issue by nya-elimuai** [elimu-ai/web3-smart-contracts#26]

**Comment by hhio618** [comment]
Added here: https://kovan.etherscan.io/address/0xc05871ac6a349a7067b260ee37496333133b058c using this transaction: https://kovan.etherscan.io/tx/0xaffdc285015b9b54cc3b78a733b40bb5f92e72379e5423e5987db3869d3d311d

**Comment by hhio618** [comment]
Deployed here: https://kovan.etherscan.io/tx/0x1a559268bbf04b34f9f7d2ba241e4f41b5697b2ff25b3144276a73fe0f563b78, using tx: https://kovan.etherscan.io/tx/0x1a559268bbf04b34f9f7d2ba241e4f41b5697b2ff25b3144276a73fe0f563b78

**Comment by nya-elimuai** [comment]
> Deployed here: https://kovan.etherscan.io/tx/0x1a559268bbf04b34f9f7d2ba241e4f41b5697b2ff25b3144276a73fe0f563b78, using tx: https://kovan.etherscan.io/tx/0x1a559268bbf04b34f9f7d2ba241e4f41b5697b2ff25b3144276a73fe0f563b78

@hhio618 Thank you! 🙂
