### ISSUE TITLE
First round of Uniswap rewards refactoring

### ISSUE THREAD

**Issue by nya-elimuai** [elimu-ai/web3-smart-contracts#40]
- [x] Add comments to variables where they are missing #59 
- [x] Add comments to functions where they are missing #59 
- [x] Rename variables
  - [x] https://github.com/elimu-ai/web3-smart-contracts/pull/52
- [x] #55 
  - [x] `deposit()` → `depositPoolTokens()`
  - [x] `withdraw()` → `withdrawPoolTokens()`
- [x] Rename events
  - [x] `Deposited` → `PoolTokensDeposited`
  - [x] `Withdrawn` → `PoolTokensWithdrawn`
- [x] #57 
  - [x] Exclude `contracts/mocks/` from code coverage
- [x] Reduce amount of code
- [ ] ~~Replace `ERC20Mock.sol` with an import from OpenZeppelin/Solmate?~~

**Comment by hhio618** [comment]
@nya-elimuai Any ideas for reducing the code?

**Comment by nya-elimuai** [comment]
> @nya-elimuai Any ideas for reducing the code?

@hhio618 Would it be possible to delete the `rewardPerTokenDeposited` variable? Can it be replaced by a function?
